import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {sample,adversarial} from '../../src/examples.mjs';
import {compile,parseProject} from '../../src/core.mjs';
import {exportsFor} from '../../src/export.mjs';
import {verifyPlotlyConsumer} from './plotly-consumer.mjs';
const out='tests/browser/artifacts';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,chromiumSandbox:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await context.newPage(),done=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));let acceptDialog=false;
page.on('dialog',async d=>acceptDialog?d.accept():d.dismiss());
const base=process.env.BASE_URL||'http://127.0.0.1:4173';
const step=async(name,fn)=>{await fn();done.push(name);console.log('PASS '+name);};
async function load(p){await page.locator('#format').selectOption('project');await page.locator('#source').fill(JSON.stringify(p));await page.locator('#read').click();await expect(page.locator('#title')).toHaveValue(p.title);await page.locator('#apply').click();await expect(page.locator('#dirty')).not.toBeVisible();await expect(page.locator('#retained-weight')).toHaveText(String(compile(p).retainedWeight));}
async function download(key,basename){const pending=page.waitForEvent('download');await page.locator(`[data-export="${key}"]`).click();const file=await pending;const path=`${out}/${basename||file.suggestedFilename()}`;await file.saveAs(path);return readFile(path,'utf8');}
try{
await step('initial sample has exact policy totals, unique IDs and seven traceable links',async()=>{await page.goto(base);await expect(page.locator('#retained-weight')).toHaveText('10');await expect(page.locator('#boundary-totals')).toHaveText('10 · 10');await expect(page.locator('#flow path[data-link]')).toHaveCount(7);assert.equal(await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(n=>n.id);return ids.length===new Set(ids).size;}),true);await page.screenshot({path:`${out}/desktop-en.png`,fullPage:true});});
await step('keyboard link selection and Japanese interface retain exact contributing row',async()=>{const link=page.locator('#flow path[data-link="l1"]');await link.focus();await page.keyboard.press('Enter');await expect(page.locator('#flow path[data-link="l1"]')).toBeFocused();await expect(page.locator('#detail tbody tr')).toHaveCount(1);await expect(page.locator('#detail')).toContainText('p01');await page.keyboard.press('ArrowRight');await expect(page.locator('#flow path[data-link="l2"]')).toBeFocused();await expect(page.locator('#detail')).toContainText('p03');await page.keyboard.press('ArrowLeft');await expect(page.locator('#flow path[data-link="l1"]')).toBeFocused();await page.locator('[data-lang="ja"]').click();await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.locator('#detail')).toContainText('p01');await page.screenshot({path:`${out}/desktop-ja.png`,fullPage:true});await page.locator('[data-lang="en"]').click();});
await step('policy draft locks exports; exclusion changes every boundary to six',async()=>{await page.locator('#policy').selectOption('exclude');await expect(page.locator('#dirty')).toBeVisible();await expect(page.locator('[data-export="flourish"]')).toBeDisabled();await expect(page.locator('#retained-weight')).toHaveText('10');await page.locator('#apply').click();await expect(page.locator('#retained-weight')).toHaveText('6');await expect(page.locator('#boundary-totals')).toHaveText('6 · 6');const excluded=JSON.parse(await download('exclusions','excluded-policy.json'));assert.deepEqual(excluded.exclusions,[{row:4,itemId:'p04',weight:4,missingStages:[1]}]);await page.locator('#policy').selectOption('sentinel');await page.locator('#apply').click();await expect(page.locator('#retained-weight')).toHaveText('10');});
await step('invalid roles retain last compiled work and revert clears draft',async()=>{await page.locator('#id-column').selectOption('1');await page.locator('#apply').click();await expect(page.locator('#notice')).toContainText('one role');await expect(page.locator('#retained-weight')).toHaveText('10');await expect(page.locator('[data-export="project"]')).toBeDisabled();await page.locator('#revert').click();await expect(page.locator('#id-column')).toHaveValue('0');await expect(page.locator('#dirty')).not.toBeVisible();});
await step('display overrides change presentation while preserving node IDs and raw path evidence',async()=>{await page.locator('#display-node').selectOption('s1n1');await page.locator('#display-text').fill('Email bulletin');await expect(page.locator('[data-export="plotly"]')).toBeDisabled();await page.locator('#apply-display').click();await expect(page.locator('#retained-weight')).toHaveText('10');await expect(page.locator('#links')).toContainText('Email bulletin');await expect(page.locator('#detail')).toContainText('Newsletter');const renamed=parseProject(await download('project','display-project.json'));assert.deepEqual(renamed.displayLabels,[{stage:0,label:'Newsletter',display:'Email bulletin'}]);assert.deepEqual(compile(renamed).links,compile(sample).links);await load(sample);});
await step('malformed CSV survives language change; TSV reads quoted line breaks and literal formulas',async()=>{await page.locator('#source').fill('A,B\nwrong');await page.locator('#format').selectOption('csv');await page.locator('#read').click();await expect(page.locator('#notice')).toContainText('entries');await page.locator('[data-lang="ja"]').click();await expect(page.locator('#source')).toHaveValue('A,B\nwrong');await page.locator('[data-lang="en"]').click();await page.locator('#format').selectOption('tsv');await page.locator('#source').fill('Before\tAfter\n"line\nvalue"\t=1+1');await page.locator('#read').click();await page.locator('#apply').click();await expect(page.locator('#retained-weight')).toHaveText('1');await expect(page.locator('#detail')).toContainText('=1+1');assert.equal(await page.evaluate(()=>window.injected),undefined);});
await step('example replacement cancellation and confirmation preserve deliberate choices',async()=>{await page.locator('#title').fill('Keep me');await page.locator('[data-example="sample"]').click();await expect(page.locator('#title')).toHaveValue('Keep me');acceptDialog=true;await page.locator('[data-example="sample"]').click();await expect(page.locator('#title')).toHaveValue(sample.title);acceptDialog=false;await expect(page.locator('#dirty')).not.toBeVisible();});
await step('all nine handoff downloads equal deterministic exports and project reimports',async()=>{const files=exportsFor(sample);for(const expected of files){const actual=await download(expected.key);assert.equal(actual,expected.content,expected.key);}assert.deepEqual(parseProject(await readFile(`${out}/pathspool-project.json`,'utf8')),sample);await page.locator('#format').selectOption('project');await page.locator('#file').setInputFiles({name:'project.json',mimeType:'application/json',buffer:Buffer.from(await readFile(`${out}/pathspool-project.json`))});await expect(page.locator('#source')).toHaveValue(files.find(f=>f.key==='project').content);await page.locator('#read').click();await page.locator('#apply').click();await expect(page.locator('#retained-weight')).toHaveText('10');});
await step('machine versus spreadsheet CSV is explicit and JSON evidence remains exact',async()=>{await load(adversarial);const machine=await download('contributions','identity-machine.csv');assert.ok(machine.includes('"=SUM(1,2)"'));await page.locator('#csv-mode').selectOption('spreadsheet');const safe=await download('contributions','identity-spreadsheet.csv');assert.ok(safe.includes('"\'=SUM(1,2)"'));assert.deepEqual(parseProject(await download('project','identity-project.json')),adversarial);await page.locator('#csv-mode').selectOption('machine');});
await step('repeated file reads and malformed UTF-8 distinguish a legitimate replacement character',async()=>{const before=await page.locator('#source').inputValue();await page.locator('#file').setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from([255])});await expect(page.locator('#notice')).toContainText('File is not valid UTF-8');await expect(page.locator('#source')).toHaveValue(before);for(let i=0;i<2;i++){await page.locator('#file').setInputFiles({name:'same.csv',mimeType:'text/csv',buffer:Buffer.from('A,B\n\uFFFD,x')});await expect(page.locator('#source')).toHaveValue('A,B\n\uFFFD,x');}await page.locator('#format').selectOption('csv');await page.locator('#read').click();await page.locator('#apply').click();await expect(page.locator('#retained-weight')).toHaveText('1');await expect(page.locator('#detail')).toContainText('\uFFFD');});
await step('late asynchronous file reads cannot replace a newer sample',async()=>{await page.evaluate(()=>{window.originalRead=File.prototype.arrayBuffer;File.prototype.arrayBuffer=function(){return new Promise(resolve=>{window.releaseRead=()=>window.originalRead.call(this).then(resolve);});};});await page.locator('#file').setInputFiles({name:'late.csv',mimeType:'text/csv',buffer:Buffer.from('A,B\nold,old')});await expect.poll(()=>page.evaluate(()=>typeof window.releaseRead)).toBe('function');acceptDialog=true;await page.locator('[data-example="sample"]').click();await expect(page.locator('#title')).toHaveValue(sample.title);acceptDialog=false;await page.evaluate(async()=>{File.prototype.arrayBuffer=window.originalRead;await window.releaseRead();});await expect(page.locator('#source')).not.toHaveValue('A,B\nold,old');await expect(page.locator('#retained-weight')).toHaveText('10');});
await step('link filtering and provenance pagination retain exact row evidence',async()=>{const many=structuredClone(sample);many.table.rows=Array.from({length:45},(_,i)=>[`p${i+1}`,'A','B','C','1']);await load(many);await page.locator('#boundary').selectOption('1');await expect(page.locator('#links [data-link]')).toHaveCount(1);await page.locator('#links [data-link]').click();await expect(page.locator('#detail tbody tr')).toHaveCount(20);await page.locator('[data-row-page="1"]').click();await expect(page.locator('#detail tbody tr').first()).toContainText('p21');await page.locator('[data-row-page="1"]').click();await expect(page.locator('#detail tbody tr')).toHaveCount(5);await expect(page.locator('[data-row-page="1"]')).toBeDisabled();await page.locator('#search').fill('no-match');await expect(page.locator('#links [data-link]')).toHaveCount(0);});
await step('high-cardinality ID columns can be staged before assigning bounded stage roles',async()=>{const input='ID,Before,After,Weight\n'+Array.from({length:301},(_,i)=>`item${i+1},A,B,1`).join('\n');await page.locator('#format').selectOption('csv');await page.locator('#source').fill(input);await page.locator('#read').click();await expect(page.locator('#stage-count')).toHaveValue('4');await expect(page.locator('#mapping')).toBeEnabled();await page.locator('#stage-count').selectOption('2');await page.locator('[data-stage="0"]').selectOption('1');await page.locator('[data-stage="1"]').selectOption('2');await page.locator('#id-column').selectOption('0');await page.locator('#weight-column').selectOption('3');await page.locator('#apply').click();await expect(page.locator('#retained-weight')).toHaveText('301');await expect(page.locator('#flow .flow-node')).toHaveCount(2);});
await step('maximum 5000 rows, six stages and 300 nodes export all 25000 contributions',async()=>{const max={schema:'pathspool.project.v1',title:'Maximum synthetic paths',table:{columns:['S1','S2','S3','S4','S5','S6','ID','Weight'],rows:Array.from({length:5000},(_,i)=>[...Array.from({length:6},(_,s)=>`N${(i+s*7)%50}`),`r${i+1}`,'1'])},mapping:{stages:[0,1,2,3,4,5],id:6,weight:7},missing:'sentinel'};await load(max);await expect(page.locator('#flow .flow-node')).toHaveCount(300);const contributions=JSON.parse(await download('contributions-json','maximum-contributions.json'));assert.equal(contributions.contributions.length,25000);assert.equal(parseProject(await download('project','maximum-project.json')).table.rows.length,5000);await page.screenshot({path:`${out}/maximum.png`,fullPage:true});});
await step('wide labels and hostile markup remain escaped and contained in the preview',async()=>{const p=structuredClone(sample);p.title='<script>window.injected=1</script>';p.table.columns[1]='W'.repeat(100);p.table.rows[0][1]='W'.repeat(160);p.table.rows[1][1]='界'.repeat(160);p.table.rows[2][2]='<img src=x onerror=bad>';await load(p);assert.equal(await page.evaluate(()=>window.injected),undefined);await expect(page.locator('#flow img,#flow script')).toHaveCount(0);const labels=await page.locator('#flow .node-label,#flow .stage-text').evaluateAll(els=>els.map(el=>({text:el.textContent,width:el.getBBox().width,limit:el.classList.contains('node-label')?134:190,font:getComputedStyle(el).font})));for(const label of labels)assert.ok(label.width<=label.limit+2,JSON.stringify(label));await page.screenshot({path:`${out}/wide-labels.png`,fullPage:true});});
await step('responsive 768, 390 and 320 layouts preserve language controls and functional mapping',async()=>{await load(sample);for(const width of [768,390,320]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow at ${width}`);for(const language of ['ja','en']){await page.locator(`[data-lang="${language}"]`).click();await expect(page.locator('html')).toHaveAttribute('lang',language);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow ${language} at ${width}`);for(const button of ['ja','en']){const m=await page.locator(`[data-lang="${button}"]`).evaluate(el=>{const r=document.createRange();r.selectNodeContents(el);return{lines:new Set([...r.getClientRects()].map(x=>Math.round(x.top))).size,right:el.getBoundingClientRect().right,viewport:innerWidth};});assert.equal(m.lines,1,JSON.stringify(m));assert.ok(m.right<=m.viewport);}if(width<=390)assert.equal(await page.locator('#detail tbody tr').first().evaluate(el=>getComputedStyle(el).display),'grid');await page.screenshot({path:`${out}/mobile-${language}-${width}.png`,fullPage:true});}}await page.locator('#policy').selectOption('exclude');await page.locator('#apply').click();await expect(page.locator('#retained-weight')).toHaveText('6');});
await step('handoff guide is standalone, escaped and printable; screen print warns about partial views',async()=>{await load(sample);const html=await download('guide');const report=await context.newPage();await report.setContent(html);await expect(report.locator('h1')).toHaveText(sample.title);await expect(report.locator('table').nth(1).locator('tbody tr')).toHaveCount(7);await expect(report.locator('script')).toHaveCount(0);await report.emulateMedia({media:'print'});await report.pdf({path:`${out}/handoff-guide.pdf`,format:'A4',printBackground:true});await report.screenshot({path:`${out}/handoff-guide.png`,fullPage:true});await report.close();await page.emulateMedia({media:'print'});await expect(page.locator('.print-note')).toBeVisible();await page.emulateMedia({media:'screen'});});
await step('no external application requests or uncaught page errors',async()=>{const urls=[],fresh=await context.newPage();fresh.on('request',r=>urls.push(r.url()));await fresh.goto(base);await expect(fresh.locator('#retained-weight')).toHaveText('10');assert.ok(urls.every(url=>url.startsWith(base+'/')),urls.join('\n'));await fresh.close();assert.deepEqual(errors,[]);});
await step('actual pinned Plotly consumer renders synthetic exports with explicit zero/empty observations',async()=>{await verifyPlotlyConsumer(context,out);});
await writeFile(`${out}/results.json`,JSON.stringify({status:'passed',chromiumSandbox:true,checks:done,uncaughtErrors:errors},null,2));
}catch(error){await page.screenshot({path:`${out}/failure.png`,fullPage:true}).catch(()=>{});await writeFile(`${out}/results.json`,JSON.stringify({status:'failed',chromiumSandbox:true,checks:done,error:String(error),uncaughtErrors:errors},null,2));throw error;}finally{await context.close();await browser.close();}
