import test from 'node:test';
import assert from 'node:assert/strict';
import {createDOM} from './dom-stub.mjs';
import {sample,adversarial} from '../src/examples.mjs';
let serial=0;
async function app(){const dom=createDOM();globalThis.document=dom.document;globalThis.window=dom.window;dom.window.confirm=()=>true;await import(`../src/app.mjs?domtest=${serial++}`);const get=id=>dom.document.getElementById(id);return{...dom,get,change:async(id,value,type='change')=>{const el=get(id);el.value=value;await el.emit(type);},click:async selector=>{const el=dom.document.querySelector(selector);assert.ok(el,selector);await el.emit('click');await get('app').emit('click',{target:el});}};}
test('actual initial handlers show sample weight, comparison and unambiguous SVG IDs',async()=>{const a=await app();assert.equal(a.get('retained-weight').textContent,'10');assert.equal(a.get('boundary-totals').textContent,'10 · 10');const ids=a.document.querySelectorAll('[id]').map(x=>x.id);assert.equal(ids.length,new Set(ids).size);assert.equal(a.get('dirty').hidden,true);assert.equal(a.document.querySelector('[data-export="flourish"]').disabled,false);});
test('actual policy change locks exports then apply updates all results',async()=>{const a=await app();await a.change('policy','exclude');assert.equal(a.get('dirty').hidden,false);assert.equal(a.document.querySelector('[data-export="project"]').disabled,true);assert.equal(a.get('retained-weight').textContent,'10');await a.click('#apply');assert.equal(a.get('retained-weight').textContent,'6');assert.equal(a.get('boundary-totals').textContent,'6 · 6');assert.equal(a.document.querySelector('[data-export="project"]').disabled,false);});
test('malformed source survives language switch and reversion restores applied work',async()=>{const a=await app();await a.change('source','A,B\nwrong','input');assert.equal(a.get('apply').disabled,true);await a.click('#read');assert.equal(a.get('source').value,'A,B\nwrong');await a.click('[data-lang="ja"]');assert.equal(a.get('source').value,'A,B\nwrong');assert.equal(a.document.documentElement.lang,'ja');await a.click('#revert');assert.equal(a.get('dirty').hidden,true);assert.equal(a.get('retained-weight').textContent,'10');});
test('mapping error retains old result; input and title text never execute markup',async()=>{const a=await app();await a.change('title','<img src=x onerror=bad>','input');await a.change('id-column','1');await a.click('#apply');assert.match(a.get('notice').textContent,/one role/);assert.equal(a.get('retained-weight').textContent,'10');assert.equal(a.get('title').value,'<img src=x onerror=bad>');assert.equal(a.document.querySelectorAll('img').length,0);});
test('JSON read and compile keeps policies and exact table values',async()=>{const a=await app();await a.change('format','project');await a.change('source',JSON.stringify(adversarial),'input');await a.click('#read');assert.equal(a.get('weight-column').value,'4');await a.click('#apply');assert.equal(a.get('retained-weight').textContent,'6');assert.equal(a.get('title').value,adversarial.title);});
test('pending file read cannot overwrite a newer sample or source edit',async()=>{const a=await app();let resolve;const promise=new Promise(r=>resolve=r);const input=a.get('file');input.files=[{size:4,arrayBuffer:()=>promise}];const pending=input.emit('change');await a.click('[data-example="edge"]');resolve(new TextEncoder().encode('old').buffer);await pending;assert.equal(a.get('title').value,adversarial.title);assert.ok(!a.get('source').value.includes('old'));});
test('real Blob invalid UTF-8 rejects without losing source; same valid file can be read repeatedly',async()=>{const a=await app(),before=a.get('source').value;let input=a.get('file');input.files=[new Blob([new Uint8Array([255])])];await input.emit('change');assert.match(a.get('notice').textContent,/valid UTF-8/);assert.equal(a.get('source').value,before);for(let i=0;i<2;i++){input=a.get('file');input.files=[new Blob(['A,B\n\uFFFD,x'])];await input.emit('change');assert.equal(a.get('source').value,'A,B\n\uFFFD,x');}await a.click('#read');await a.click('#apply');assert.equal(a.get('retained-weight').textContent,'1');});
test('filters and link choice change visible rows while retaining selection focus',async()=>{const a=await app();await a.change('boundary','1');const list=a.get('links').querySelectorAll('[data-link]');assert.ok(list.length>0);assert.ok(list.every(x=>x.textContent.includes('2→3')));const chosen=list[0];await a.get('app').emit('click',{target:chosen});assert.ok(a.get('detail').textContent.includes(chosen.dataset.link));assert.equal(a.document.activeElement.dataset.link,chosen.dataset.link);await a.change('search','impossible','input');assert.equal(a.get('links').querySelectorAll('[data-link]').length,0);});
test('SVG links support roving arrow navigation and preserve focus after rerender',async()=>{const a=await app();const path=a.get('flow').querySelector('path[data-link]');const event=await a.get('app').emit('keydown',{target:path,key:'Enter'});assert.equal(event.defaultPrevented,true);assert.equal(a.document.activeElement.dataset.link,path.dataset.link);assert.equal(a.document.activeElement.tagName,'PATH');await a.get('app').emit('keydown',{target:a.document.activeElement,key:'ArrowRight'});assert.equal(a.document.activeElement.dataset.link,'l2');assert.equal(a.get('flow').querySelectorAll('path[tabindex="0"]').length,1);await a.get('app').emit('keydown',{target:a.document.activeElement,key:'End'});assert.equal(a.document.activeElement.dataset.link,'l7');await a.get('app').emit('keydown',{target:a.document.activeElement,key:'Home'});assert.equal(a.document.activeElement.dataset.link,'l1');});
test('cancelled sample replacement preserves unsaved source; applied work prompts on unload',async()=>{const a=await app();await a.change('source','unsaved','input');a.window.confirm=()=>false;await a.click('[data-example="edge"]');assert.equal(a.get('source').value,'unsaved');const before=await a.window.emit('beforeunload');assert.equal(before.defaultPrevented,true);});
test('display editing locks exports, commits appearance only and stage changes clear overrides',async()=>{const a=await app();await a.change('display-text','Email bulletin','input');assert.equal(a.get('dirty').hidden,false);assert.equal(a.document.querySelector('[data-export="project"]').disabled,true);await a.click('#apply-display');assert.equal(a.get('dirty').hidden,true);assert.ok(a.get('links').textContent.includes('Email bulletin'));assert.ok(a.get('detail').textContent.includes('Newsletter'));assert.equal(a.get('retained-weight').textContent,'10');const stage=a.document.querySelector('[data-stage="0"]');stage.value='0';await stage.emit('change');assert.equal(a.get('display-editor').disabled,true);await a.click('#revert');assert.equal(a.get('display-text').value,'Email bulletin');});
