import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {compile,parseProject,validateProject} from '../src/core.mjs';
import {exportsFor,csv,projectJSON,plotlyFigure,guideHTML,escapePlotlyText} from '../src/export.mjs';
import {sample,adversarial} from '../src/examples.mjs';
const clone=structuredClone;
function pythonCSV(value){const r=spawnSync('python3',['-c','import csv,io,json,sys; print(json.dumps(list(csv.reader(io.StringIO(sys.stdin.read(),newline=""))),ensure_ascii=False))'],{input:value,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout);}
test('all nine exports are deterministic and never mutate the input',()=>{for(const p of [sample,adversarial])for(const mode of ['machine','spreadsheet']){const before=clone(p),a=exportsFor(p,mode),b=exportsFor(p,mode);assert.deepEqual(a,b);assert.deepEqual(p,before);assert.equal(a.length,9);assert.equal(new Set(a.map(f=>f.name)).size,9);}});
test('Flourish machine contract uses collision-free IDs and explicit value and both step fields',()=>{const r=compile(adversarial),file=exportsFor(adversarial).find(f=>f.key==='flourish'),[header,...rows]=pythonCSV(file.content);assert.deepEqual(header,['Source','Target','Value','Step from','Step to','Source label','Target label','Source missing','Target missing','Link ID','Source display label','Target display label']);const n=new Map(r.nodes.map(n=>[n.id,n]));assert.equal(rows.length,r.links.length);for(const [i,row] of rows.entries()){const l=r.links[i];assert.deepEqual(row,[l.source,l.target,String(l.value),String(l.boundary+1),String(l.boundary+2),n.get(l.source).label??'',n.get(l.target).label??'',String(n.get(l.source).missing),String(n.get(l.target).missing),l.id,'','']);assert.match(row[0],/^[a-z0-9]+$/);assert.match(row[1],/^[a-z0-9]+$/);}});
test('machine CSV exact text survives independent Python parsing, including formulas and multiline labels',()=>{const rows=[['Name','Value'],['=SUM(1,2)',' a '],['\t+cmd','line\r\nline'],['a"b','<script>'],['@x','日本語'],['-0','\n']];assert.deepEqual(pythonCSV(csv(rows)),rows);});
test('spreadsheet mode prefixes risky text rather than relying on quotes; numbers remain numeric',()=>{const risky=['=1+1','+2','-1','@sum','  =x','\ttext','\ntext','\rtext','\ufeff=x'];const rows=risky.map(s=>[s,4,0]);const parsed=pythonCSV(csv(rows,'spreadsheet'));assert.deepEqual(parsed,risky.map(s=>["'"+s,'4','0']));assert.deepEqual(pythonCSV(csv([['safe',"'already",' a']], 'spreadsheet')),[['safe',"'already",' a']]);assert.throws(()=>csv([], 'unknown'));});
test('CSV variants leave JSON evidence and project files identical',()=>{const machine=exportsFor(adversarial),safe=exportsFor(adversarial,'spreadsheet');for(const a of machine.filter(f=>f.mime!=='text/csv'))assert.equal(a.content,safe.find(f=>f.key===a.key).content);assert.ok(safe.find(f=>f.key==='contributions').content.includes("'=SUM"));assert.ok(!machine.find(f=>f.key==='contributions').content.includes("'=SUM"));});
test('node CSV contains exact labels and a separate missing flag',()=>{const r=compile(adversarial),[, ...rows]=pythonCSV(exportsFor(adversarial).find(f=>f.key==='nodes').content);assert.equal(rows.length,r.nodes.length);r.nodes.forEach((n,i)=>assert.deepEqual(rows[i],[n.id,String(n.index),String(n.stage+1),r.stages[n.stage],n.label??'',String(n.missing),'']));});
test('contribution CSV and JSON agree; absent and empty item IDs remain distinguishable',()=>{for(const id of [0,null]){const p=clone(sample);p.mapping.id=id;p.table.rows[0][0]='';const r=compile(p),files=exportsFor(p),[, ...rows]=pythonCSV(files.find(f=>f.key==='contributions').content);assert.deepEqual(JSON.parse(files.find(f=>f.key==='contributions-json').content).contributions,r.contributions);r.contributions.forEach((c,i)=>assert.deepEqual(rows[i],[c.linkId,String(c.row),c.itemId??'',String(c.itemId!==null),String(c.weight)]));}});
test('Plotly arrays use zero-based indices, exact safe integers and documented layout metadata',()=>{const p=clone(adversarial);p.title='<img src=x onerror=bad>';const r=compile(p),fig=plotlyFigure(r),trace=fig.data[0];assert.deepEqual(Object.keys(fig),['data','layout']);assert.equal(trace.type,'sankey');assert.equal(trace.node.label.length,r.nodes.length);assert.deepEqual(trace.link.value,r.links.map(l=>l.value));for(const [i,l]of r.links.entries()){assert.equal(r.nodes[trace.link.source[i]].id,l.source);assert.equal(r.nodes[trace.link.target[i]].id,l.target);}assert.deepEqual(trace.node.customdata.map(n=>n.label),r.nodes.map(n=>n.label));assert.equal(fig.layout.title.text,'&lt;img src=x onerror=bad&gt;');assert.equal(fig.layout.meta.policy,p.missing);assert.deepEqual(fig.layout.meta.stageNames,r.stages);assert.ok(trace.node.label.some(s=>s.includes('&lt;done&gt;')));assert.deepEqual(JSON.parse(exportsFor(p).find(f=>f.key==='plotly').content),fig);});
test('paths retain complete sequences, exclusions preserve omitted rows and weights',()=>{const p=clone(sample);p.missing='exclude';const r=compile(p),files=exportsFor(p),paths=JSON.parse(files.find(f=>f.key==='paths').content),exclusions=JSON.parse(files.find(f=>f.key==='exclusions').content);assert.deepEqual(paths.paths,r.paths);assert.deepEqual(paths.nodes,r.nodes);assert.deepEqual(exclusions.exclusions,[{row:4,itemId:'p04',weight:4,missingStages:[1]}]);});
test('project export round-trips exact labels, raw weights and all unmapped columns',()=>{const p=clone(sample);p.table.rows[0][0]='\uFFFD & < \r\n';p.table.rows[0][4]='0003';assert.deepEqual(parseProject(projectJSON(p)),p);for(const which of ['id','weight']){const invalid=clone(sample);invalid.mapping[which]=-0;assert.throws(()=>validateProject(invalid),/invalid column/);}const invalid=clone(sample);invalid.mapping.stages=[-0,1];invalid.mapping.id=null;assert.throws(()=>validateProject(invalid),/invalid column/);});
test('standalone guide escapes all source text and contains no executable source markup',()=>{const p=clone(sample);p.title='<script>alert(1)</script>';p.table.columns[1]='<img src=x onerror=bad>';p.table.rows[0][1]='</td><script>bad</script>';const html=guideHTML(p,compile(p));assert.ok(html.includes('&lt;script&gt;alert(1)&lt;/script&gt;'));const r=spawnSync('python3',['-c',`from html.parser import HTMLParser
import json,sys
class P(HTMLParser):
 def __init__(self): super().__init__();self.tags=[];self.attrs=[];self.parts=[]
 def handle_starttag(self,t,a): self.tags.append(t);self.attrs.extend(a)
 def handle_data(self,s): self.parts.append(s)
p=P();p.feed(sys.stdin.read());print(json.dumps({'tags':p.tags,'attrs':p.attrs,'text':''.join(p.parts)}))`],{input:html,encoding:'utf8'});assert.equal(r.status,0,r.stderr);const parsed=JSON.parse(r.stdout);assert.ok(!parsed.tags.includes('script'));assert.ok(!parsed.tags.includes('img'));assert.ok(!parsed.attrs.some(([k])=>k.startsWith('on')));assert.ok(parsed.text.includes(p.title));assert.ok(parsed.text.includes(p.table.rows[0][1]));});
test('model API rejects serialization hooks, accessors and extra array properties without executing them',()=>{let called=false;for(const kind of ['hook','accessor','symbol','prototype']){const p=clone(sample);if(kind==='hook')p.table.rows[0].toJSON=()=>{called=true;return[];};if(kind==='accessor')Object.defineProperty(p,'title',{enumerable:true,get:()=>{called=true;return'bad';}});if(kind==='symbol')p.table.rows[0][Symbol('extra')]='lost';if(kind==='prototype')Object.setPrototypeOf(p,{toJSON(){called=true;return{};}});assert.throws(()=>projectJSON(p));}assert.equal(called,false);});
test('Plotly text preserves literal quotes while escaping markup and pre-existing entity text',()=>{const text=`"quoted" 'single' & <b>x</b> &quot; &#39;`,escaped=`"quoted" 'single' &amp; &lt;b&gt;x&lt;/b&gt; &amp;quot; &amp;#39;`;assert.equal(escapePlotlyText(text),escaped);const p=clone(sample);p.title=text;p.table.rows[0][1]=text;p.displayLabels=[{stage:1,label:'Design lab',display:text}];const figure=JSON.parse(exportsFor(p).find(f=>f.key==='plotly').content);assert.equal(figure.layout.title.text,escaped);const source=figure.data[0].node.customdata.findIndex(n=>n.label===text),override=figure.data[0].node.customdata.findIndex(n=>n.displayLabel===text);assert.ok(source>=0&&override>=0);for(const i of [source,override])assert.equal(figure.data[0].node.label[i],`${figure.data[0].node.customdata[i].id} · ${escaped}`);assert.equal(figure.data[0].node.customdata[source].label,text);assert.equal(figure.data[0].node.customdata[override].displayLabel,text);});
